### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BlenderUser** [gethiox/GXAudioVisualisation#8]
It gives me an error everytime i try to bake it. I dont know what the problem is, but you can find the error underneath:

Traceback (most recent call last):
File "C:\Users\mert0073\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\GxAV.py", line 593, in execute
gxbake()
File "C:\Users\mert0073\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\GxAV.py", line 465, in gxbake
bpy.ops.object.select_all(action="DESELECT")
File "C:\Program Files\Blender Foundation\Blender\2.77\scripts\modules\bpy\ops.py", line 189, in call
ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.select_all.poll() failed, context is incorrect

location: <unknown location>:-1﻿

**Comment by gethiox** [comment]
I know it might be a little late, but can you send me .blend file where this problem happen? (xD)
I will close this issue when new version will be released because I can't reproduce the problem with that one traceback.
